[workspace]
members = [
    "crates/ferrotex-cli",
    "crates/ferrotex-core",
    "crates/ferrotex-log",
    "crates/ferrotex-syntax",
    "crates/ferrotexd",
    "crates/ferrotex-package",
    "crates/ferrotex-math-semantics",
    "crates/ferrotex-analysis",
    "crates/ferrotex-build",
    "crates/ferrotex-dap",
    "fuzz",
]
resolver = "2"

[workspace.package]
version = "0.24.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/jxoesneon/FerroTeX"
homepage = "https://jxoesneon.github.io/FerroTeX/"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
manual_strip = "warn"
assertions_on_constants = "warn"

[profile.release]
lto = true
strip = true
codegen-units = 1


